# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.firefox.options import Options

class TestDvwalogindatabasecreate():
  @pytest.fixture()
  def name(pytestconfig):
    return pytestconfig.getoption("url")
    
  def setup_method(self, method):
    options = Options()
    options.headless = True
    self.driver = webdriver.Firefox(options=options)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_dvwalogindatabasecreate(self, url):
    self.driver.get({name})
    self.driver.set_window_size(787, 693)
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").send_keys("admin")
    self.driver.find_element(By.NAME, "password").send_keys("password")
    self.driver.find_element(By.ID, "wrapper").click()
    self.driver.find_element(By.NAME, "Login").click()
    element = self.driver.find_element(By.NAME, "Login")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.NAME, "create_db").click()
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").send_keys("admin")
    self.driver.find_element(By.NAME, "password").send_keys("password")
    self.driver.find_element(By.ID, "wrapper").click()
    self.driver.find_element(By.NAME, "Login").click()
  
