# Generated by Selenium IDE
import pytest

from selenium import webdriver
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.common.by import By

# http://dvwa-samp-1bo0rckbc73ci.eba-jewkgbxg.us-east-2.elasticbeanstalk.com/login.php"

@pytest.fixture()
def url(pytestconfig):
    return pytestconfig.getoption("url")

@pytest.fixture(scope="session")      
def get_driver():
    global driver
    options = Options()
    options.add_argument("--headless")
    driver = webdriver.Firefox(options=options)
    yield
    driver.close()
    
@pytest.mark.usefixtures("get_driver")
def test_data(url):
    target_url = url
    # Test name: login&configure
    # Step # | name | target | value
    # 1 | open | /login.php | 
    driver.get(target_url)
    # 2 | setWindowSize | 787x695 | 
    driver.set_window_size(787, 695)
    # 3 | click | name=username | 
    driver.find_element(By.NAME, "username").click()
    # 4 | type | name=username | admin
    driver.find_element(By.NAME, "username").send_keys("admin")
    # 5 | click | id=wrapper | 
    driver.find_element(By.ID, "wrapper").click()
    # 6 | click | name=password | 
    driver.find_element(By.NAME, "password").click()
    # 7 | type | name=password | password
    driver.find_element(By.NAME, "password").send_keys("password")
    # 8 | click | id=content | 
    driver.find_element(By.ID, "content").click()
    # 9 | click | name=Login | 
    driver.find_element(By.NAME, "Login").click()
    # 10 | click | name=create_db | 
    
    '''
    driver.find_element(By.NAME, "create_db").click()
    # 11 | click | linkText=login | 
    driver.find_element(By.LINK_TEXT, "login").click()
    # 12 | click | name=username | 
    driver.find_element(By.NAME, "username").click()
    # 13 | type | name=username | admin
    driver.find_element(By.NAME, "username").send_keys("admin")
    # 14 | click | id=wrapper | 
    driver.find_element(By.ID, "wrapper").click()
    # 15 | click | name=password | 
    driver.find_element(By.NAME, "password").click()
    # 16 | type | name=password | password
    driver.find_element(By.NAME, "password").send_keys("password")
    # 17 | click | id=wrapper | 
    driver.find_element(By.ID, "wrapper").click()
    # 18 | click | name=Login | 
    driver.find_element(By.NAME, "Login").click()
    '''
