# This is a basic workflow to help you get started with Actions

name: Dev-SIS-TuffleHog

# Controls when the workflow will run
on:
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@master
        name: github checkout
        
      - name: trufflehog-actions-scan
        uses: edplato/trufflehog-actions-scan@master
        
      - name: trufflehog-actions-check
        if: always()
        uses: UnicornGlobal/trufflehog-actions-scan@v1.0.0
        
  
      - name: check local directory
        if: always()
        run: |
          ls -l
