name: Dev-SAST-snyk
on:
  workflow_dispatch:
jobs:
  Dev-SAST-snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: check local directory
        run: |
          ls -l
          
