# This is a basic workflow to help you get started with Actions

name: test_ping

# Controls when the workflow will run
on:
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test_ping:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
       
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Github Runner Public IP
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Print Github Runner Public IP
        run: |
          echo ${{ steps.ip.outputs.ipv4 }}
          echo ${{ steps.ip.outputs.ipv6 }}
      
      - name: whitelist runner IP Address
        #aws s3 sync ./build s3://test-bucket
        run: |
          aws ec2 create-network-acl-entry --network-acl-id acl-00c482d30cef5efcf --ingress --rule-number 90 --cidr-block ${{ steps.ip.outputs.ipv4 }}/32 --rule-action allow --protocol -1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-2'
          
      # Runs a set of commands using the runners shell
      # http://dvwa-samp-11vtckhdz9fty.eba-mfpqrsmp.us-east-2.elasticbeanstalk.com/
      - name: Run a multi-line script
        run: |
          curl ifconfig.me > test.txt
          cat test.txt
          curl -X GET https://google.com > test.txt
          cat test.txt
          curl -X GET http://awseb-e-w-AWSEBLoa-1KZ40B03SHEUP-871702028.us-east-2.elb.amazonaws.com -m 15 > test.txt
          cat test.txt
          
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          
      - name: Install Selenium
        run: |
          pip install selenium
          pip install pytest
          
      - name: Run pytest test_selenium.py --browser=chrome --headless
        run: |
          pytest test_selenium.py
          
      - name: cleanup whitelist runner IP Address
        #aws s3 sync ./build s3://test-bucket
        run: |
          aws ec2 delete-network-acl-entry --network-acl-id acl-00c482d30cef5efcf --ingress --rule-number 90
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-2'
