
name: test-workflow-jobs

on:  
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Run a bash command
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
